-- SQL script to create separate tables for admins and tenants

-- Create admins table
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert admin user with email admin@gmail.com and password 'admin123'
-- Replace the password hash below with the actual hash generated by PHP's password_hash function
INSERT INTO admins (username, email, password) VALUES (
    'admin@gmail.com',
    'admin@gmail.com',
    '$2y$10$e0NRXQ6q6Xq6Q6q6Q6q6QO6q6Q6q6Q6q6Q6q6Q6q6Q6q6Q6q6Q6q'
);

-- Create tenants table (similar to existing users table for tenants)
CREATE TABLE IF NOT EXISTS tenants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'tenant',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Note: You will need to update your application logic to use these separate tables for authentication and registration.
